<?php
/**
 * implements hook_mail_alter()
 */
function custom_contact_form_mail_alter(&$message) { 

  // only alter contact forms
  if (!empty($message['id']) && $message['id'] == 'contact_page_mail_content') {

    $contact_message = $message['params']['contact_message'];
    $name = $contact_message->get('field_your_first_name')->getString();
	$emaiDatal = $contact_message->get('field_your_email_feild')->getString();

	/*Unsetting message body field*/
	$message['body'] = [];
	/*sending html formatted email*/

	$message['headers']  = 'MIME-Version: 1.0' . "\r\n";
	$message['headers'] .= 'Content-type: text/html; charset=UTF-8;format=flowed' . "\r\n";

     // add plain text body string into the $message['body'] array
    $message_list = array('Name' => $name ,'Email' => $emaiDatal);
    // In line css to handle Design. 					
	$newdata = 'Hello ' .$message_list['Name']. ',This a confirmation email to inform you that we have successfully received your request.Shortly you will receive a response from a company representative. We aim to respond to your query as quickly and efficiently as possible, on some occasions it may take up to 24 hours.Thank you for your patience and we look forward to connecting with you!Thanks,';
    // Assigning new message to mail body.
	$message['body']['0'] = $newdata;

	
    }
}